### ISSUE TITLE
Toggle menu doesn't work!

### ISSUE THREAD

**Issue by itsashis4u** [robdodson/collapse-toolbar#3]
I tried to use this Polymer element, to test the collapsible toggle menu button, but unfortunately it didn't work.
When I resize the browser, the anchor tags just gets stacked up instead of changing to toggle mode.

What should I do?

**Comment by nmelo** [comment]
Same issue here. 
The component seems to be loading a core-a11-keys element in the shadow-dom instead of a core-overlay.
Took screenshots on side by side tabs on the same browser. 
Not working:
![screen shot 2015-02-01 at 7 19 59 pm](https://cloud.githubusercontent.com/assets/238738/5994569/aa8c779c-aa47-11e4-9ced-78f976cf069a.png)
Working:
![screen shot 2015-02-01 at 7 21 28 pm](https://cloud.githubusercontent.com/assets/238738/5994568/aa8b2d88-aa47-11e4-876b-cc63bd59daff.png)

**Comment by nmelo** [comment]
This was broken by the 0.5.1 release: 
https://blog.polymer-project.org/releases/2014/11/12/release-0.5.1/#0-5-1_coremenubutton
